PWD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("users.urls"))
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.home, name="home"),

    path('new/', login_required(LocationCreateView.as_view()), name='create'),
    
    path("view/<str:pk>/", views.view, name = "view"),
]

main/models.py
from django.db import models
from users.models import User
from django.urls import reverse
# Create your models here.

class Location(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    website_name = models.CharField(max_length=200)
    website_link = models.URLField(max_length=200, null=True)
    website_username = models.CharField(max_length=200)
    website_password = models.CharField(max_length=200)
    website_notes = models.CharField(max_length=200, null=True)
    master_password = models.CharField(max_length=200, default='')

    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.website_name

    def get_absolute_url(self):
        return reverse("home")
    

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Location
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.contrib.auth.hashers import check_password
from .encryption import *

# Create your views here.
@login_required
def home(request):
    user = request.user
    location = Location.objects.filter(author = user)
    context = {
        'location': location
    }
    return render(request, "main/home.html", context)

class LocationCreateView(CreateView):
    model = Location
    fields = [
        'website_name',
        'website_link',
        'website_username',
        'website_password',
        'website_notes',
        'master_password',
    ]

    def form_valid(self, form):
        if form.is_valid():
            user = self.request.user
            form.instance.author = user

            form_master_password = form.instance.master_password
            # the field titled "master_password" in Location model 

            user_password = self.request.user.password
            # hashed master password in database 

            if not check_password(form_master_password, user_password):
                messages.error(self.request, "Error: Invalid link.")
                return redirect("create")
            else: 
                website_password = form.instance.website_password

                form.instance.website_password = encrypt(form_master_password.encode(), website_password.encode())

                form.instance.website_password = encrypt(form_master_password.encode(), form.instance.website_password.encode())
                # to encrypt twice

                form.instance.master_password = ''
                # Clears out "master_password" of Location so that it isn't stored database 
                # If not, it will be stored as plain text
                # Storing plain text passwords has to be avoided at all costs
                
                return super().form_valid(form)
        else:
            messages.error(self.request, "Error")
            messages.add_message(self.request, messages.ERROR, 'Error')


@login_required
def view(request, pk):
    user = request.user
    try:
        location = Location.objects.get(id=pk, author=user)
    except:
        messages.error(request, "Error: Invalid link.")
        return redirect("home")
    if request.method =="POST":
        user_password = location.website_password
        password = request.POST.get("password_field")
        if decrypted := decrypt(password.encode(), user_password):
            decrypted = decrypt(password.encode(), decrypted)
            context = {
                'location': location,
                'decrypted': decrypted,
                'confirmed': True, # user provided the right password
            }
            return render(request, "main/detail_view.html", context)
        else:
            messages.error(request, "Incorrect Master Password!")
    
    context = {
        'location': location,
    }

    return render(request, "main/detail_view.html", context)

main/templates/main/detail_view.html
{%extends "main/home.html"%}
{% load static %}
{% block title %}
<title>Saved Passwords: {{location}}</title>
{% endblock title %}
{%block content%}
    <div class="div-container">
        <div>
            <h1 class = "main-color" style="display:inline; position: relative;text-align: left">Name: </h1><h1 style="display:inline; word-wrap: break-word">{{location}}</h1>
        </div>
        <div>
            <br/>
            <h1 class = "main-color" style="display:inline;">Link: </h1><h1 style="display:inline; word-wrap: break-word">{{location.website_link}}</h1>
        </div>
        <div>
            <br/>
            <h1 class = "main-color" style="display:inline;">Username: </h1><h1 style="display:inline; word-wrap: break-word">{{location.website_username}}</h1>
        </div>
        <div>
            <br/>
            <h1 class = "main-color" style="display:inline;">Notes: </h1><h1 style="display:inline; word-wrap: break-word">{{location.website_notes}}</h1>
        </div>
        <div>
            {% if not confirmed%}
                <form method = "POST">
                    {% csrf_token %}
                    <h2 class = "main-color">Provide master password to view {{location}} password:</h2>

                    <input type="password" name = "password_field" name="Password">

                    <input type="submit" value="Submit">
                </form>
            {% endif %}
            <div>
                {% if confirmed %}
                    <br/>
                    <h1 class = "main-color" style="display:inline;">Password: </h1>
                    <h1 style="display:inline; word-wrap: break-word">{{decrypted}}</h1>
                {% else %}
                    <h1>{{message}}</h1>
                {% endif %}
            </div>
        </div>
    </div>
{%endblock content%}

main/templates/main/home.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title %}
        <title>Password Manager</title>
        {% endblock  %}
        <meta name="description" content="secure password manager.">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css2?family=Oxanium&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'CSS/style.css'  %}">
        <link rel="icon" type="image/png" href="{% static 'images/logo.png'  %}"/>
    </head>
    <body style="text-align: center; font-family: 'Oxanium';">
        <header>
            <ul class='u-list'>
                <li>
                
                    <a href="{%url 'home'%}"><img src="{% static 'images/logo.png'  %}"
                    style="width: 31.125px; height 40px; padding: 10px;float:left"></a> 
                
                </li>

                {% if user.is_authenticated %}
                    <li class ='list'><a href="{%url 'logout'%}">Logout</a></li>
                    <li class ='list'><a href="{% url 'create' %}">Add Password</a></li>
                    <li class ='list'><a href="{% url 'account' %}">Profile</a></li>
                {% else %}
                    <li class ='list'><a href="{%url 'login'%}">Login</a></li>
                    <li class ='list'><a href="{%url 'register'%}">Register</a></li>
                {% endif %}

                
                
            </ul>
        </header>
        <main>
            <section>
                <br/>
                {% for message in messages %}
                        <div class="div-container" style="padding: 0px;width: 30%">
                            <h1>{{message}}</h1>
                        </div>
                        <br />
                        <br />
                    {% endfor %}
                {% block content %}
                    {% if location %}
                        {% for row in location %}
                            <div class = "div-container">
                                <h1 style="text-align: center; font-size:40px"><a class='link' href = "{% url 'view' row.id %}">{{row}}</a></h1>
                            </div>
                            <br/>
                            <br/>
                        {% endfor %}
                    {% else %}
                        <button type="button" style="border-radius: 100px; height: 70px; box-shadow: 1px 2px 6px -1px;"><p1 style="text-align: center; font-size:40px;"><a class='link' href = "{% url 'create' %}">Store Your First Password!</a></p1></button> 
                    {% endif %}
                {% endblock content %}
            </section>
        </main>
        <footer>

        </footer>
        <script src="" async defer></script>
    </body>
</html>

main/templates/main/location_form.html
{%extends "main/home.html"%}
{% load static %}
{% block title %}
<title>Add Passwords</title>
{% endblock title %}
{%block content%}
    <form method="POST">
        {% csrf_token %}
        <div class = "div-container">
            <p1 class = "main-color"
                <p><label for="id_website_name">Website name:</label> <input type="text"    name="website_name" maxlength="50" required id="id_website_name"></p>

                <p><label for="id_website_link">Website link:</label> <input type="url"         name="website_link" maxlength="180" required id="id_website_link"></p>

                <p><label for="id_website_username">Website username:</label> <input type="text"        name="website_username" maxlength="50" required id="id_website_username"></p>

                <p><label for="id_website_password">Website password:</label> <input type="password"        name="website_password" maxlength="50" required id="id_website_password"></p>

                <p><label for="id_website_notes">Website notes:</label> <input type="text"      name="website_notes" maxlength="50" required id="id_website_notes"></p>

                <p><label for="id_master_password">Master password:</label> <input type="password"      name="master_password" maxlength="55" required id="id_master_password"></p>
                <input style = "border-radius:10px;"type="submit" value="Submit">
            </p1>
        </div>
    </form>
{%endblock content%}